language: ruby
rvm: 2.1.0
notifications:
  hipchat:
    rooms:
      secure: DeGmcWjTugnJDCC2BNqDh53Sstook7Ybb0dVwMYZLMFdRuvxL5JciiX5djlrgTIlW2VVYKtmOfuwDGCYxOsqnhdkpuzOBZkp+YjDvPpzDHELXROlJRtQpo+sbhAeG0GKdHPj40ANxzRYLJ6bsUu7sASmRRLE0KpVPDFfbx2HkAo=
