language: ruby
rvm: 2.2.1
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create db:migrate
script:
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: L6cuPE761h5Mp+uVQupgtsuWkLqkr6sXQnNOEGPozRUQ/UAShRJrb6+4qJ4rFbWzbawaW6+sM4WjyKydP+VWiIrpmehd+6iq5TrDerjoOdCTURT/TLnFIca2dnXe5+tzDBGuINIA7EdrxZn6Ht+NhKtHL5+g7rGjw2xU8RPyKuA=
  app:
    master: nekostagram
    staging: nekostagram-staging
  on:
    repo: ruedap/nekostagram
