language: ruby
rvm: 2.2.2
cache: bundler
sudo: false
before_script:
- npm install
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create db:migrate
script:
- bundle exec rake
